{"topicSections":[{"title":"Instance Methods","identifiers":["doc:\/\/com.mimik.cocoapod.EdgeEngine\/documentation\/EdgeEngine\/Edge\/getStatus()","doc:\/\/com.mimik.cocoapod.EdgeEngine\/documentation\/EdgeEngine\/Edge\/start(with:nodeId:nodeName:license:workingDirectory:startupParameters:)","doc:\/\/com.mimik.cocoapod.EdgeEngine\/documentation\/EdgeEngine\/Edge\/stop()"]}],"sections":[],"relationshipsSections":[{"identifiers":["doc:\/\/com.mimik.cocoapod.EdgeEngine\/objc(cs)NSObject"],"title":"Inherits From","type":"inheritsFrom","kind":"relationships"},{"type":"conformsTo","title":"Conforms To","identifiers":["doc:\/\/com.mimik.cocoapod.EdgeEngine\/objc(pl)NSObject","doc:\/\/com.mimik.cocoapod.EdgeEngine\/s7CVarArgP","doc:\/\/com.mimik.cocoapod.EdgeEngine\/s28CustomDebugStringConvertibleP","doc:\/\/com.mimik.cocoapod.EdgeEngine\/s23CustomStringConvertibleP","doc:\/\/com.mimik.cocoapod.EdgeEngine\/SQ","doc:\/\/com.mimik.cocoapod.EdgeEngine\/SH"],"kind":"relationships"}],"schemaVersion":{"major":0,"minor":3,"patch":0},"metadata":{"fragments":[{"kind":"keyword","text":"class"},{"kind":"text","text":" "},{"kind":"identifier","text":"Edge"}],"navigatorTitle":[{"text":"Edge","kind":"identifier"}],"externalID":"c:objc(cs)Edge","title":"Edge","symbolKind":"class","role":"symbol","modules":[{"name":"EdgeEngine"}],"roleHeading":"Class"},"identifier":{"url":"doc:\/\/com.mimik.cocoapod.EdgeEngine\/documentation\/EdgeEngine\/Edge","interfaceLanguage":"swift"},"variants":[{"paths":["\/documentation\/edgeengine\/edge"],"traits":[{"interfaceLanguage":"swift"}]},{"paths":["\/documentation\/edgeengine\/edge"],"traits":[{"interfaceLanguage":"occ"}]}],"kind":"symbol","primaryContentSections":[{"declarations":[{"tokens":[{"kind":"keyword","text":"class"},{"text":" ","kind":"text"},{"text":"Edge","kind":"identifier"}],"languages":["swift"],"platforms":["iOS"]}],"kind":"declarations"}],"hierarchy":{"paths":[["doc:\/\/com.mimik.cocoapod.EdgeEngine\/documentation\/EdgeEngine"]]},"references":{"doc://com.mimik.cocoapod.EdgeEngine/s28CustomDebugStringConvertibleP":{"identifier":"doc:\/\/com.mimik.cocoapod.EdgeEngine\/s28CustomDebugStringConvertibleP","title":"Swift.CustomDebugStringConvertible","type":"unresolvable"},"doc://com.mimik.cocoapod.EdgeEngine/objc(cs)NSObject":{"identifier":"doc:\/\/com.mimik.cocoapod.EdgeEngine\/objc(cs)NSObject","title":"NSObject","type":"unresolvable"},"doc://com.mimik.cocoapod.EdgeEngine/documentation/EdgeEngine/Edge/stop()":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"stop","kind":"identifier"},{"text":"()","kind":"text"}],"navigatorTitle":[{"text":"stop","kind":"identifier"}],"type":"topic","title":"stop()","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.mimik.cocoapod.EdgeEngine\/documentation\/EdgeEngine\/Edge\/stop()","abstract":[],"url":"\/documentation\/edgeengine\/edge\/stop()"},"doc://com.mimik.cocoapod.EdgeEngine/s23CustomStringConvertibleP":{"identifier":"doc:\/\/com.mimik.cocoapod.EdgeEngine\/s23CustomStringConvertibleP","title":"Swift.CustomStringConvertible","type":"unresolvable"},"doc://com.mimik.cocoapod.EdgeEngine/SH":{"identifier":"doc:\/\/com.mimik.cocoapod.EdgeEngine\/SH","title":"Swift.Hashable","type":"unresolvable"},"doc://com.mimik.cocoapod.EdgeEngine/documentation/EdgeEngine/Edge/getStatus()":{"fragments":[{"text":"func","kind":"keyword"},{"text":" ","kind":"text"},{"text":"getStatus","kind":"identifier"},{"text":"() -> ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:s5Int32V","text":"Int32"}],"navigatorTitle":[{"text":"getStatus","kind":"identifier"}],"type":"topic","title":"getStatus()","role":"symbol","kind":"symbol","identifier":"doc:\/\/com.mimik.cocoapod.EdgeEngine\/documentation\/EdgeEngine\/Edge\/getStatus()","abstract":[],"url":"\/documentation\/edgeengine\/edge\/getstatus()"},"doc://com.mimik.cocoapod.EdgeEngine/s7CVarArgP":{"identifier":"doc:\/\/com.mimik.cocoapod.EdgeEngine\/s7CVarArgP","title":"Swift.CVarArg","type":"unresolvable"},"doc://com.mimik.cocoapod.EdgeEngine/documentation/EdgeEngine/Edge":{"abstract":[],"type":"topic","fragments":[{"text":"class","kind":"keyword"},{"kind":"text","text":" "},{"text":"Edge","kind":"identifier"}],"role":"symbol","url":"\/documentation\/edgeengine\/edge","identifier":"doc:\/\/com.mimik.cocoapod.EdgeEngine\/documentation\/EdgeEngine\/Edge","navigatorTitle":[{"kind":"identifier","text":"Edge"}],"kind":"symbol","title":"Edge"},"doc://com.mimik.cocoapod.EdgeEngine/documentation/EdgeEngine":{"role":"collection","identifier":"doc:\/\/com.mimik.cocoapod.EdgeEngine\/documentation\/EdgeEngine","kind":"symbol","title":"EdgeEngine","type":"topic","url":"\/documentation\/edgeengine","abstract":[{"type":"text","text":"mimik Client Library provides a programmatic way to work with the edgeEngine Runtime to access information about the mobile device on which the application is running."}]},"doc://com.mimik.cocoapod.EdgeEngine/SQ":{"identifier":"doc:\/\/com.mimik.cocoapod.EdgeEngine\/SQ","title":"Swift.Equatable","type":"unresolvable"},"doc://com.mimik.cocoapod.EdgeEngine/objc(pl)NSObject":{"identifier":"doc:\/\/com.mimik.cocoapod.EdgeEngine\/objc(pl)NSObject","title":"ObjectiveC.NSObjectProtocol","type":"unresolvable"},"doc://com.mimik.cocoapod.EdgeEngine/documentation/EdgeEngine/Edge/start(with:nodeId:nodeName:license:workingDirectory:startupParameters:)":{"role":"symbol","type":"topic","kind":"symbol","identifier":"doc:\/\/com.mimik.cocoapod.EdgeEngine\/documentation\/EdgeEngine\/Edge\/start(with:nodeId:nodeName:license:workingDirectory:startupParameters:)","abstract":[],"navigatorTitle":[{"kind":"identifier","text":"startWith:nodeId:nodeName:licenseString:workingDirectory:startupParameters:"}],"url":"\/documentation\/edgeengine\/edge\/start(with:nodeid:nodename:license:workingdirectory:startupparameters:)","title":"start(with:nodeId:nodeName:license:workingDirectory:startupParameters:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"text":"start","kind":"identifier"},{"kind":"text","text":"("},{"kind":"externalParam","text":"with"},{"text":": ","kind":"text"},{"preciseIdentifier":"s:s5Int32V","text":"Int32","kind":"typeIdentifier"},{"text":", ","kind":"text"},{"kind":"externalParam","text":"nodeId"},{"kind":"text","text":": "},{"preciseIdentifier":"s:SS","kind":"typeIdentifier","text":"String"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"nodeName"},{"kind":"text","text":": "},{"text":"String","preciseIdentifier":"s:SS","kind":"typeIdentifier"},{"text":"!, ","kind":"text"},{"kind":"externalParam","text":"license"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","text":"String","preciseIdentifier":"s:SS"},{"kind":"text","text":"!, "},{"kind":"externalParam","text":"workingDirectory"},{"text":": ","kind":"text"},{"kind":"typeIdentifier","preciseIdentifier":"s:SS","text":"String"},{"text":"!, ","kind":"text"},{"kind":"externalParam","text":"startupParameters"},{"text":": [","kind":"text"},{"text":"AnyHashable","preciseIdentifier":"s:s11AnyHashableV","kind":"typeIdentifier"},{"kind":"text","text":" : "},{"text":"Any","kind":"keyword"},{"text":"]!) -> ","kind":"text"},{"preciseIdentifier":"s:s5Int32V","text":"Int32","kind":"typeIdentifier"}]}},"variantOverrides":[{"traits":[{"interfaceLanguage":"occ"}],"patch":[{"value":"occ","op":"replace","path":"\/identifier\/interfaceLanguage"},{"path":"\/metadata\/roleHeading","op":"replace","value":"Class"},{"path":"\/metadata\/title","value":"Edge","op":"replace"},{"op":"replace","path":"\/metadata\/symbolKind","value":"class"},{"op":"replace","path":"\/metadata\/fragments","value":[{"text":"Edge","kind":"identifier"}]},{"path":"\/metadata\/navigatorTitle","value":[{"text":"Edge","kind":"identifier"}],"op":"replace"},{"op":"replace","path":"\/topicSections","value":[{"title":"Instance Methods","identifiers":["doc:\/\/com.mimik.cocoapod.EdgeEngine\/documentation\/EdgeEngine\/Edge\/getStatus()","doc:\/\/com.mimik.cocoapod.EdgeEngine\/documentation\/EdgeEngine\/Edge\/start(with:nodeId:nodeName:license:workingDirectory:startupParameters:)","doc:\/\/com.mimik.cocoapod.EdgeEngine\/documentation\/EdgeEngine\/Edge\/stop()"]}]},{"value":[{"identifiers":["doc:\/\/com.mimik.cocoapod.EdgeEngine\/objc(cs)NSObject"],"type":"inheritsFrom","kind":"relationships","title":"Inherits From"}],"op":"replace","path":"\/relationshipsSections"},{"op":"add","path":"\/seeAlsoSections","value":null},{"path":"\/primaryContentSections\/0","value":{"declarations":[{"platforms":["iOS"],"languages":["occ"],"tokens":[{"kind":"keyword","text":"@interface"},{"text":" ","kind":"text"},{"kind":"identifier","text":"Edge"},{"text":" : ","kind":"text"},{"preciseIdentifier":"c:objc(cs)NSObject","kind":"typeIdentifier","text":"NSObject"}]}],"kind":"declarations"},"op":"replace"},{"op":"replace","path":"\/references\/doc:~1~1com.mimik.cocoapod.EdgeEngine~1documentation~1EdgeEngine~1Edge~1stop()\/title","value":"stop"},{"value":[{"text":"- ","kind":"text"},{"kind":"identifier","text":"stop"}],"path":"\/references\/doc:~1~1com.mimik.cocoapod.EdgeEngine~1documentation~1EdgeEngine~1Edge~1stop()\/fragments","op":"replace"},{"path":"\/references\/doc:~1~1com.mimik.cocoapod.EdgeEngine~1documentation~1EdgeEngine~1Edge~1getStatus()\/title","op":"replace","value":"getStatus"},{"op":"replace","path":"\/references\/doc:~1~1com.mimik.cocoapod.EdgeEngine~1documentation~1EdgeEngine~1Edge~1getStatus()\/fragments","value":[{"kind":"text","text":"- "},{"kind":"identifier","text":"getStatus"}]},{"value":"Edge","path":"\/references\/doc:~1~1com.mimik.cocoapod.EdgeEngine~1documentation~1EdgeEngine~1Edge\/title","op":"replace"},{"path":"\/references\/doc:~1~1com.mimik.cocoapod.EdgeEngine~1documentation~1EdgeEngine~1Edge\/fragments","op":"replace","value":[{"text":"Edge","kind":"identifier"}]},{"path":"\/references\/doc:~1~1com.mimik.cocoapod.EdgeEngine~1documentation~1EdgeEngine~1Edge~1start(with:nodeId:nodeName:license:workingDirectory:startupParameters:)\/title","op":"replace","value":"startWith:nodeId:nodeName:licenseString:workingDirectory:startupParameters:"},{"path":"\/references\/doc:~1~1com.mimik.cocoapod.EdgeEngine~1documentation~1EdgeEngine~1Edge~1start(with:nodeId:nodeName:license:workingDirectory:startupParameters:)\/fragments","value":[{"text":"- ","kind":"text"},{"text":"startWith:nodeId:nodeName:licenseString:workingDirectory:startupParameters:","kind":"identifier"}],"op":"replace"}]}]}